### ISSUE TITLE
PromisePoolError: Operation timeout

### ISSUE THREAD

**Issue by alacret** [supercharge/promise-pool#55]
Getting error in very long running tasks

**Comment by marcuspoehls** [comment]
@alacret Hey Angel, can you please share more details? Is that timeout coming from another resource and not from the promise pool?

**Comment by alacret** [comment]
@marcuspoehls I made a mistake copying the error name, I updated the title of the Issue. this is the trace:

<img width="1728" alt="Screen Shot 2022-08-19 at 7 54 46 AM" src="https://user-images.githubusercontent.com/918895/185613061-cd6139c9-e0c2-441d-ab1e-a8e009a09bca.png">

```
Aug 19 01:06:08 ip-172-31-23-202 worker: PromisePoolError: Operation timeout
Aug 19 01:06:08 ip-172-31-23-202 worker: at Function.createFrom (/var/app/current/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
Aug 19 01:06:08 ip-172-31-23-202 worker: at PromisePoolExecutor.saveErrorFor (/var/app/current/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:440:66)
Aug 19 01:06:08 ip-172-31-23-202 worker: at PromisePoolExecutor.handleErrorFor (/var/app/current/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:370:20)
Aug 19 01:06:08 ip-172-31-23-202 worker: at /var/app/current/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:313:24
Aug 19 01:06:08 ip-172-31-23-202 worker: at runMicrotasks (<anonymous>)
Aug 19 01:06:08 ip-172-31-23-202 worker: at runNextTicks (internal/process/task_queues.js:60:5)
Aug 19 01:06:08 ip-172-31-23-202 worker: at listOnTimeout (internal/timers.js:526:9)
Aug 19 01:06:08 ip-172-31-23-202 worker: at processTimers (internal/timers.js:500:7) {
Aug 19 01:06:08 ip-172-31-23-202 worker: raw: ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
Aug 19 01:06:08 ip-172-31-23-202 worker: at ConnectionManager.getConnection (/var/app/current/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:15)
Aug 19 01:06:08 ip-172-31-23-202 worker: at runMicrotasks (<anonymous>)
Aug 19 01:06:08 ip-172-31-23-202 worker: at runNextTicks (internal/process/task_queues.js:60:5)
Aug 19 01:06:08 ip-172-31-23-202 worker: at listOnTimeout (internal/timers.js:526:9)
Aug 19 01:06:08 ip-172-31-23-202 worker: at processTimers (internal/timers.js:500:7)
Aug 19 01:06:08 ip-172-31-23-202 worker: at async /var/app/current/node_modules/sequelize/lib/sequelize.js:301:26
Aug 19 01:06:08 ip-172-31-23-202 worker: at async MySQLQueryInterface.select (/var/app/current/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
Aug 19 01:06:08 ip-172-31-23-202 worker: at async Function.findAll (/var/app/current/node_modules/sequelize/lib/model.js:1134:21)
Aug 19 01:06:08 ip-172-31-23-202 worker: at async Function.findOne (/var/app/current/node_modules/sequelize/lib/model.js:1228:12)
Aug 19 01:06:08 ip-172-31-23-202 worker: at async processCaseUpdates (/var/app/current/modules/rdn/services.js:109:26)
Aug 19 01:06:08 ip-172-31-23-202 worker: at async PromisePoolExecutor.handler (/var/app/current/modules/rdn/services.js:415:7) {
Aug 19 01:06:08 ip-172-31-23-202 worker: parent: TimeoutError: Operation timeout
Aug 19 01:06:08 ip-172-31-23-202 worker: at Timeout.<anonymous> (/var/app/current/node_modules/sequelize-pool/lib/Deferred.js:17:25)
Aug 19 01:06:08 ip-172-31-23-202 worker: at listOnTimeout (internal/timers.js:557:17)
Aug 19 01:06:08 ip-172-31-23-202 worker: at processTimers (internal/timers.js:500:7),
Aug 19 01:06:08 ip-172-31-23-202 worker: original: TimeoutError: Operation timeout
Aug 19 01:06:08 ip-172-31-23-202 worker: at Timeout.<anonymous> (/var/app/current/node_modules/sequelize-pool/lib/Deferred.js:17:25)
Aug 19 01:06:08 ip-172-31-23-202 worker: at listOnTimeout (internal/timers.js:557:17)
Aug 19 01:06:08 ip-172-31-23-202 worker: at processTimers (internal/timers.js:500:7)
Aug 19 01:06:08 ip-172-31-23-202 worker: },

```

**Comment by marcuspoehls** [comment]
Thank you for sharing the details. The actual error is a `ConnectionAcquireTimeoutError` coming from Sequelize. The promise pool wraps the original error using a `PromisePoolError` instance. The original error is available on the promise pool error using the `error.raw` property.

**Comment by alacret** [comment]
@marcuspoehls thanks!
